### ISSUE TITLE
Running GEX against a remote or configurable instance

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/gex#19]
Is it possible to execute the gex binary that communicates with a Cosmos-SDK-based chain other than `localhost` or whatever is running locally? It would be nice to be able to run gex against either a remote node or a custom address/port.

**Comment by toschdev** [comment]
I've tried that once and it did not work. Would like to find out why. Maybe it was due to some config or firewall.
An optional flag to input a remote node would be cool.

**Comment by toschdev** [comment]
The port is configurable using for example `gex -p 27657`. 
Which was mostly needed when running more instances on localhost.

**Comment by alexanderbez** [comment]
But can it talk to a remote instance not on `localhost`?

**Comment by toschdev** [comment]
no
