### ISSUE TITLE
Allow port to be specified to connect to a different chain

### ISSUE THREAD

**Issue by andynog** [cosmos/gex#2]
Hi guys,

Great work. The tool seems promising. I'd like to request a feature in case you are not working on it yet. In my IBC testing I usually have two chains running and one of the them doesn't have the default port (26657). So it would be nice that when running `gex` if you could specify the port to listen on and connect to a non-default chain port, something like `gex -p [PORT]`

Thanks,

Andy.

**Comment by toschdev** [comment]
Yes, that's something we considered already and should be easy to implement. Was waiting for the request and can implement it soon! Thanks for the Issue!

**Comment by toschdev** [comment]
@andynog Maybe you can tell if this satisfies your needs? https://github.com/cosmos/gex/pull/3

**Comment by andynog** [comment]
Hi @Tosch110, I've tested and it works. Thanks so much!

**Comment by ksbomj** [comment]
Hi @toschdev 

I created [pr](https://github.com/cosmos/gex/pull/22) that adds more flags for specifying host, transport security, and updated readme. Please let me know if it's fine. We are using this tool a lot for quick debugging and it's good to have them without hacking `gex` every time when a connection to the remote host is required.

Thank you!
