### ISSUE TITLE
Application crashes if the chain is stopped

### ISSUE THREAD

**Issue by andynog** [cosmos/gex#4]
**Describe the bug**

The tui crashes if you stop the chain that is listening to.

**To Reproduce**

* Start a chain in a terminal windown e.g. `$ gaiad start`
* On another terminal run the tool `$ gex`
* Go back to the terminal that was running the chain and stop it
* The tui will show the error below

```
panic: Get "http://localhost:26657/heal": dial tcp [::1]:26657: connect: connection refused
go routine 55 [running]:
...
```

**Expected behavior**

Probably in the routine listening on the port, some error handling could gracefully exit the tool or if possible (maybe more complex), show an error in the `Health` widget.

**Screenshot**

![gex_error](https://user-images.githubusercontent.com/45477427/100124896-31a0a000-2e4a-11eb-865d-64864c81fd51.png)

**Comment by toschdev** [comment]
@andynog Mind to try this branch #6 
Would be great to get your feedback on this

**Comment by andynog** [comment]
OK @Tosch110 I will give it a try later today. Thanks!

**Comment by andynog** [comment]
Seems to be working now. When I stop the chain doesn't crash anymore just show a red dot, if I start the chain again it can re-connect which is nice. The only thing is that the dashboard lines seems to be a little bit out of order (see image). This is running from a terminal on a Linux machine (Fedora) not sure if it matters but just providing some context.

![gex](https://user-images.githubusercontent.com/45477427/102106525-af7b1a00-3dfe-11eb-82e8-bc15ee8f5198.png)

**Comment by toschdev** [comment]
Thanks, I will try to replicate and find a solution.

**Comment by toschdev** [comment]
I'll still merge it, I cannot find a solution as it is without major rewrite. Having a bit dizzy layout, you probably want to restart. Better than a terminal in a bad state
